# Use Node.js image
FROM node:18

# Set working directory
WORKDIR /react-app

# Copy package.json and install dependencies
COPY /react-app/package.json .
COPY /react-app/package-lock.json .
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Expose the Vite development port
EXPOSE 5173

WORKDIR /react-app

# Run the Vite dev server
CMD ["npm", "run", "dev"]
