# filepath: .circleci/config.yml
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest ./tests
      - store_artifacts:
        path: test-results.log
        destination: test-results.log

workflows:
  version: 2
  test:
    jobs:
      - test