"""Create Basic DB

Revision ID: 2a6312edbd04
Revises: 
Create Date: 2025-02-09 14:52:03.569936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6312edbd04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.VARCHAR(), nullable=False),
    sa.Column('Password', sa.VARCHAR(), nullable=False),
    sa.Column('Email', sa.VARCHAR(), nullable=True),
    sa.Column('NumberOfRating', sa.Integer(), nullable=False),
    sa.Column('CurrentRating', sa.Integer(), nullable=False),
    sa.Column('PhoneNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Username')
    )
    op.create_index(op.f('ix_profiles_UserID'), 'profiles', ['UserID'], unique=False)
    op.create_table('cards',
    sa.Column('CardID', sa.Integer(), nullable=False),
    sa.Column('OwnerID', sa.Integer(), nullable=False),
    sa.Column('CardQuality', sa.String(), nullable=False),
    sa.Column('CardName', sa.String(), nullable=False),
    sa.Column('IsValidated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['OwnerID'], ['profiles.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CardID')
    )
    op.create_index(op.f('ix_cards_CardID'), 'cards', ['CardID'], unique=False)
    op.create_table('auctions',
    sa.Column('AuctionID', sa.Integer(), nullable=False),
    sa.Column('CardID', sa.Integer(), nullable=False),
    sa.Column('SellerID', sa.Integer(), nullable=False),
    sa.Column('MinimumIncrement', sa.Float(), nullable=False),
    sa.Column('Status', sa.VARCHAR(), nullable=False),
    sa.Column('EndTime', sa.DateTime(), nullable=False),
    sa.Column('HighestBidderID', sa.Integer(), nullable=False),
    sa.Column('HighestBid', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['CardID'], ['cards.CardID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SellerID'], ['cards.OwnerID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AuctionID')
    )
    op.create_index(op.f('ix_auctions_AuctionID'), 'auctions', ['AuctionID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_AuctionID'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_cards_CardID'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_profiles_UserID'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
