"""Update profiles table to only have UserID and Email

Revision ID: 55f62e3bf1a8
Revises: b8e62e3157ee
Create Date: 2025-02-16 22:55:39.714065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f62e3bf1a8'
down_revision: Union[str, None] = 'b8e62e3157ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'UserID',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('profiles', 'PhoneNumber')
    op.drop_column('profiles', 'NumberOfRating')
    op.drop_column('profiles', 'Password')
    op.drop_column('profiles', 'Username')
    op.drop_column('profiles', 'CurrentRating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('CurrentRating', sa.INTEGER(), nullable=False))
    op.add_column('profiles', sa.Column('Username', sa.VARCHAR(), nullable=False))
    op.add_column('profiles', sa.Column('Password', sa.VARCHAR(), nullable=False))
    op.add_column('profiles', sa.Column('NumberOfRating', sa.INTEGER(), nullable=False))
    op.add_column('profiles', sa.Column('PhoneNumber', sa.INTEGER(), nullable=True))
    op.alter_column('profiles', 'UserID',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
