"""Initial migration

Revision ID: 564176daca18
Revises: 2a6312edbd04
Create Date: 2025-02-16 15:22:30.125864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564176daca18'
down_revision: Union[str, None] = '2a6312edbd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('CardName', sa.VARCHAR(), nullable=False))
    op.add_column('auctions', sa.Column('ImageURL', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'ImageURL')
    op.drop_column('auctions', 'CardName')
    # ### end Alembic commands ###
