"""Create notifications table

Revision ID: b0dda1edb18f
Revises: 4c2fb5936e29
Create Date: 2025-02-17 16:54:07.857864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dda1edb18f'
down_revision: Union[str, None] = '4c2fb5936e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('CardName', sa.VARCHAR(), nullable=False))
    op.add_column('auctions', sa.Column('ImageURL', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'ImageURL')
    op.drop_column('auctions', 'CardName')
    # ### end Alembic commands ###
