"""Update profiles table to only have UserID and Email

Revision ID: b8e62e3157ee
Revises: 4c2fb5936e29
Create Date: 2025-02-16 22:54:08.162139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e62e3157ee'
down_revision: Union[str, None] = '4c2fb5936e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
